
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy-reader
  namespace: monitoring-plane

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy-pod-reader
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - namespaces
    verbs:
      - get
      - list
      - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy-pod-reader-binding
subjects:
  - kind: ServiceAccount
    name: alloy-reader
    namespace: monitoring-plane
roleRef:
  kind: ClusterRole
  name: alloy-pod-reader
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: monitoring-plane
spec:
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      serviceAccountName: alloy-reader
      containers:
        - name: alloy
          image: grafana/alloy:v1.13.2
          args:
            - run
            - /etc/alloy/config.alloy
            - --storage.path=/var/lib/alloy/data
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
              readOnly: true
            - name: alloy-data
              mountPath: /var/lib/alloy
          resources:
            requests:
              cpu: "40m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          securityContext:
            readOnlyRootFilesystem: true
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        runAsNonRoot: true
      volumes:
        - name: config
          configMap:
            name: alloy-config
        - name: alloy-data
          emptyDir: {}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring-plane
data:
  config.alloy: |
    loki.source.kubernetes "pods" {
      targets    = discovery.kubernetes.pods.targets
      forward_to = [loki.process.logs.receiver]
    }

    discovery.kubernetes "pods" {
      role = "pod"
    }

    loki.process "logs" {
      forward_to = [loki.write.default.receiver]
    }

    loki.write "default" {
      endpoint {
        url = "http://svc-loki:3100/loki/api/v1/push"
      }
    }

    prometheus.scrape "janitor" {
      targets = [
        { __address__ = "http://svc-janitor:3001" },
      ]
      forward_to = [prometheus.remote_write.mimir.receiver]
    }
  
    prometheus.remote_write "mimir" {
      endpoint {
        url = "http://svc-mimir:8081/api/v1/push"

        headers = {
          "X-Scope-OrgID" = "default",
        }
      }
    }
