apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: monitoring-plane
spec:
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      containers:
        - name: alloy
          image: grafana/alloy:v1.13.2
          args:
            - run
            - /etc/alloy/config.alloy
            - --storage.path=/var/lib/alloy/data
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
            - name: varlog
              mountPath: /var/log
            - name: varlibdocker
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: alloy-data
              mountPath: /var/lib/alloy
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          securityContext:
            readOnlyRootFilesystem: true
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        runAsNonRoot: true
      volumes:
        - name: config
          configMap:
            name: alloy-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdocker
          hostPath:
            path: /var/lib/docker/containers
        - name: alloy-data
          emptyDir: {}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring-plane
data:
  config.alloy: |
    loki.source.kubernetes "pods" {
      targets    = discovery.kubernetes.pods.targets
      forward_to = [loki.process.logs.receiver]
    }

    discovery.kubernetes "pods" {
      role = "pod"
    }

    loki.process "logs" {
      stage.logfmt {
        mapping = { "timestamp" = "", "msg" = "", "service" = "", "host" = "", "endpoint" = "", "job" = "", "jobId" = "" }
      }

      forward_to = [loki.write.default.receiver]
    }

    loki.write "default" {
      endpoint {
        url = "http://svc-loki:3100/loki/api/v1/push"
      }
    }
