services:
  frontend:
    build:
      context: ./project-overengineer-fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./status-api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    depends_on:
      - redis

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile-master
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  redis-replica:
    build:
      context: ./redis
      dockerfile: Dockerfile-replica
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_MASTER_HOST: ${REDIS_MASTER_HOST}
      REDIS_MASTER_PORT: ${REDIS_MASTER_PORT}
      REDIS_MASTER_PASSWORD: ${REDIS_MASTER_PASSWORD}
    deploy:
      replicas: 2
    depends_on:
      - redis

  redis-sentinel:
    build:
      context: ./redis
      dockerfile: Dockerfile-sentinel
    ports:
      - "26379:26379"
    depends_on:
      - redis
      - redis-replica

  redis-sentinel-replica:
    build:
      context: ./redis
      dockerfile: Dockerfile-sentinel
    deploy:
      replicas: 2
    depends_on:
      - redis
      - redis-replica
