FROM hashicorp/vault:1.18

# This container is used to inject secrets into containers at runtime.

ENV SKIP_CHOWN="true"
ENV SKIP_SETCAP="true"

# Install vault certificates
RUN apk add --no-cache ca-certificates 
COPY vault-ca.crt /usr/local/share/ca-certificates/vault-ca.crt
COPY vault.crt /vault/tls/vault.crt
RUN update-ca-certificates

CMD ["vault", "agent", "-config=/vault/config/vault.hcl"]
