FROM hashicorp/vault:1.18

# Should be set to the host's non-FQDN name (e.g., vault-0).
ENV CONTAINER_NAME=""

# Should be set to either "primary" or "secondary" at runtime.
ENV HA_ROLE=""

# This container is used to automate init and unseal of the vault
# primary at apply time.

# Install vault certificate
RUN apk add --no-cache curl jq kubectl ca-certificates
COPY vault/vault-ca.crt /usr/local/share/ca-certificates/vault-ca.crt
RUN update-ca-certificates --fresh --verbose

# Include CA files for use by vault PKI
COPY vault/vault-ca.crt /vault/tls/vault-ca.crt
COPY vault/vault-ca.key /vault/tls/vault-ca.key
RUN cat /vault/tls/vault-ca.key /vault/tls/vault-ca.crt > /vault/tls/vault-ca.pem

# Run unseal script at runtime
WORKDIR /vault
COPY vault/init.sh /vault/init.sh
COPY vault/generate-pw.sh /vault/generate-pw.sh
COPY vault/unseal-vault.sh /vault/unseal-vault.sh
COPY vault/init-vault-stores.sh /vault/init-vault-stores.sh
COPY vault/renew-keys.sh /vault/renew-keys.sh
RUN chmod +x /vault/init.sh
RUN chmod +x /vault/generate-pw.sh
RUN chmod +x /vault/unseal-vault.sh
RUN chmod +x /vault/init-vault-stores.sh
RUN chmod +x /vault/renew-keys.sh
ENTRYPOINT ["/vault/init.sh"]
