FROM redis:7

ENV SENTINEL_PORT=26379
ENV REDIS_HOST=redis
ENV REDIS_PORT=6379
# ENV REDIS_PASSWORD

# Install local vault certificates
RUN apk add --no-cache ca-certificates 
COPY vault.crt /usr/local/share/ca-certificates/vault.crt
RUN update-ca-certificates

# /tmp/redis-sentinel is where config file is stored at runtime
# the rest of the filesystem is assumed to be readonly
RUN mkdir /tmp/redis-sentinel
COPY start-sentinel.sh /tmp/start-sentinel.sh
RUN chmod +x /tmp/start-sentinel.sh

ENTRYPOINT ["/tmp/start-sentinel.sh"]
