FROM redis:7

ENV REDIS_REPLICA_PORT="${REDIS_REPLICA_PORT:-6379}"
ENV REDIS_HOST="${REDIS_HOST:-redis}"
ENV REDIS_PORT="${REDIS_PORT:-6379}"
ENV REDIS_PASSWORD="${REDIS_PASSWORD}"

CMD sh -c \
    "redis-server " \
    "--bind 0.0.0.0 " \
    "--port ${REDIS_REPLICA_PORT} " \
    "--replicaof ${REDIS_HOST} ${REDIS_PORT} " \
    "--masterauth ${REDIS_PASSWORD}"
