FROM redis:7

ENV SENTINEL_PORT=26379
ENV REDIS_HOST=redis
ENV REDIS_PORT=6379
# ENV REDIS_PASSWORD

COPY start-sentinel.sh /tmp/start-sentinel.sh
RUN chmod +x /tmp/start-sentinel.sh

ENTRYPOINT ["/start-sentinel.sh"]
