FROM redis:7

ENV REDIS_REPLICA_PORT=6379
ENV REDIS_HOST=redis
ENV REDIS_PORT=6379
# ENV REDIS_PASSWORD

# Install local vault certificates
COPY vault.crt /usr/local/share/ca-certificates/vault.crt
RUN update-ca-certificates

CMD redis-server --bind 0.0.0.0 --port "$REDIS_REPLICA_PORT" --replicaof "$REDIS_HOST" "$REDIS_PORT" --masterauth "$REDIS_PASSWORD"
