FROM redis:7

# For dev; 
ENV REDIS_PORT="${REDIS_PORT:-6379}"
ENV REDIS_PASSWORD="${REDIS_PASSWORD:-b4yscx92yksfyv9c}"

CMD sh -c \
    "redis-server " \
    "--bind 0.0.0.0 " \
    "--port ${REDIS_PORT} " \
    "--requirepass ${REDIS_PASSWORD}"
