name: Deploy
on:
  workflow_dispatch:
    inputs:
      should_destroy:
        description: 'Destroy infrastructure after deployment (yes/no)'
        required: true
        default: 'yes'
        type: choice
        options:
          - 'yes'
          - 'no'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create monitoring plane namespace
        run: kubectl apply -f monitoring-plane-namespace.yaml

      - name: Deploy vault
        run: kubectl apply -f vault/service.yaml

      - name: Wait for vault apply (max 90s)
        run: kubectl rollout status statefulset/vault --timeout=90s

      - name: Deploy alloy
        run: kubectl apply -f alloy/daemonset.yaml

      - name: Deploy redis-master, redis-replica, redis-sentinel
        run: kubectl apply -f redis/service.yaml
      
      - name: Deploy janitor
        run: kubectl apply -f janitor/service.yaml
      
      - name: Deploy status-api
        run: kubectl apply -f status-api/service.yaml

      - name: Deploy ocr-worker, ollama-ocr
        run: kubectl apply -f ocr-worker/service.yaml

      - name: Deploy project-overengineer-fe
        run: kubectl apply -f project-overengineer-fe/service.yaml

      - name: Wait for apply (max 300s/service)
        run: |
          echo '[waiting for redis-master]'
          kubectl rollout status statefulset/redis-master --timeout=300s
          echo '[waiting for redis-replica]'
          kubectl rollout status statefulset/redis-replica --timeout=300s
          echo '[waiting for redis-sentinel]'
          kubectl rollout status deployment/redis-sentinel --timeout=300s
          echo '[waiting for janitor]'
          kubectl rollout status deployment/janitor --timeout=300s
          echo '[waiting for status-api]'
          kubectl rollout status deployment/status-api --timeout=300s
          echo '[waiting for ocr-worker, ollama-ocr]'
          kubectl rollout status statefulset/ocr-worker --timeout=300s
          echo '[waiting for project-overengineer-fe]'
          kubectl rollout status statefulset/project-overengineer-fe --timeout=300s

      - name: Deploy loki
        run: kubectl apply -f loki/service.yaml

      - name: Deploy mimir
        run: kubectl apply -f mimir/service.yaml

      - name: Deploy grafana
        run: kubectl apply -f grafana/service.yaml

      - name: Wait for apply (max 300s/service)
        run: |
          echo '[waiting for loki]'
          kubectl rollout status -n monitoring-plane statefulset/loki --timeout=300s
          echo '[waiting for mimir]'
          kubectl rollout status -n monitoring-plane statefulset/mimir --timeout=300s
          echo '[waiting for alloy]'
          kubectl rollout status -n monitoring-plane daemonset/alloy --timeout=300s
          echo '[waiting for grafana]'
          kubectl rollout status -n monitoring-plane statefulset/grafana --timeout=300s

      - name: Dump logs (if apply failed)
        if: failure()
        run: |
          echo 'Dumping logs...'
          echo '[vault logs]'
          kubectl logs --all-containers --selector=app=vault
          kubectl logs --all-containers --selector=app=vault --previous || true
          kubectl logs vault-0 -c vault-init || true
          echo '[redis-master logs]'
          kubectl logs --all-containers --selector=app=redis-master
          kubectl logs --all-containers --selector=app=redis-master --previous || true
          echo '[redis-replica logs]'
          kubectl logs --all-containers --selector=app=redis-replica
          kubectl logs --all-containers --selector=app=redis-replica --previous || true
          echo '[redis-sentinel logs]'
          kubectl logs --all-containers --selector=app=redis-sentinel
          kubectl logs --all-containers --selector=app=redis-sentinel --previous || true
          echo '[janitor logs]'
          kubectl logs --all-containers --selector=app=janitor
          kubectl logs --all-containers --selector=app=janitor --previous || true
          echo '[status-api logs]'
          kubectl logs --all-containers --selector=app=status-api
          kubectl logs --all-containers --selector=app=status-api --previous || true
          echo '[ocr-worker, ollama-ocr logs]'
          kubectl logs --all-containers --selector=app=ocr-worker
          kubectl logs --all-containers --selector=app=ocr-worker --previous || true
          echo '[project-overengineer-fe logs]'
          kubectl logs --all-containers --selector=app=project-overengineer-fe
          kubectl logs --all-containers --selector=app=project-overengineer-fe --previous || true
          echo '[loki logs]'
          kubectl logs -n monitoring-plane --all-containers --selector=app=loki
          kubectl logs -n monitoring-plane --all-containers --selector=app=loki --previous || true
          echo '[mimir logs]'
          kubectl logs -n monitoring-plane --all-containers --selector=app=mimir
          kubectl logs -n monitoring-plane --all-containers --selector=app=mimir --previous || true
          echo '[alloy logs]'
          kubectl logs -n monitoring-plane --all-containers --selector=app=alloy
          kubectl logs -n monitoring-plane --all-containers --selector=app=alloy --previous || true
          echo '[grafana logs]'
          kubectl logs -n monitoring-plane --all-containers --selector=app=grafana
          kubectl logs -n monitoring-plane --all-containers --selector=app=grafana --previous || true

  deploy-staging:
    runs-on: ubuntu-latest
    needs: deploy-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.3

      - name: Terraform init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ./terraform/environment/staging

      - name: Terraform apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ./terraform/environment/staging  

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-eks-staging
          aws-region: us-east-2

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name project-overengineer-staging \
            --region us-east-2

      - name: Apply default storage class to AWS
        run: kubectl apply -f k8s-aws-default-sc.yaml

      - name: Create monitoring plane namespace
        run: kubectl apply -f monitoring-plane-namespace.yaml

      - name: Deploy vault
        run: kubectl apply -f vault/service.yaml

      - name: Wait for vault apply (max 90s)
        run: kubectl rollout status statefulset/vault --timeout=90s

      - name: Deploy alloy
        run: kubectl apply -f alloy/daemonset.yaml

      - name: Deploy redis-master, redis-replica, redis-sentinel
        run: kubectl apply -f redis/service.yaml
      
      - name: Deploy janitor
        run: kubectl apply -f janitor/service.yaml
      
      - name: Deploy status-api
        run: kubectl apply -f status-api/service.yaml

      - name: Deploy ocr-worker, ollama-ocr
        run: kubectl apply -f ocr-worker/service.yaml

      - name: Deploy project-overengineer-fe
        run: kubectl apply -f project-overengineer-fe/service.yaml

      - name: Wait for apply (max 300s/service)
        run: |
          echo '[waiting for redis-master]'
          kubectl rollout status statefulset/redis-master --timeout=300s
          echo '[waiting for redis-replica]'
          kubectl rollout status statefulset/redis-replica --timeout=300s
          echo '[waiting for redis-sentinel]'
          kubectl rollout status deployment/redis-sentinel --timeout=300s
          echo '[waiting for janitor]'
          kubectl rollout status deployment/janitor --timeout=300s
          echo '[waiting for status-api]'
          kubectl rollout status deployment/status-api --timeout=300s
          echo '[waiting for ocr-worker, ollama-ocr]'
          kubectl rollout status statefulset/ocr-worker --timeout=300s
          echo '[waiting for project-overengineer-fe]'
          kubectl rollout status statefulset/project-overengineer-fe --timeout=300s

      - name: Deploy loki
        run: kubectl apply -f loki/service.yaml

      - name: Deploy mimir
        run: kubectl apply -f mimir/service.yaml

      - name: Deploy alloy
        run: kubectl apply -f alloy/daemonset.yaml

      - name: Deploy grafana
        run: kubectl apply -f grafana/service.yaml

      - name: Wait for apply (max 300s/service)
        run: |
          echo '[waiting for loki]'
          kubectl rollout status -n monitoring-plane statefulset/loki --timeout=300s
          echo '[waiting for mimir]'
          kubectl rollout status -n monitoring-plane statefulset/mimir --timeout=300s
          echo '[waiting for alloy]'
          kubectl rollout status -n monitoring-plane daemonset/alloy --timeout=300s
          echo '[waiting for grafana]'
          kubectl rollout status -n monitoring-plane statefulset/grafana --timeout=300s

      - name: Dump logs (if apply failed)
        if: failure()
        run: |
          echo 'Dumping logs...'
          echo '[vault logs]'
          kubectl logs --all-containers --selector=app=vault
          kubectl logs --all-containers --selector=app=vault --previous || true
          kubectl logs vault-0 -c vault-init || true
          echo '[redis-master logs]'
          kubectl logs --all-containers --selector=app=redis-master
          kubectl logs --all-containers --selector=app=redis-master --previous || true
          echo '[redis-replica logs]'
          kubectl logs --all-containers --selector=app=redis-replica
          kubectl logs --all-containers --selector=app=redis-replica --previous || true
          echo '[redis-sentinel logs]'
          kubectl logs --all-containers --selector=app=redis-sentinel
          kubectl logs --all-containers --selector=app=redis-sentinel --previous || true
          echo '[janitor logs]'
          kubectl logs --all-containers --selector=app=janitor
          kubectl logs --all-containers --selector=app=janitor --previous || true
          echo '[status-api logs]'
          kubectl logs --all-containers --selector=app=status-api
          kubectl logs --all-containers --selector=app=status-api --previous || true
          echo '[ocr-worker, ollama-ocr logs]'
          kubectl logs --all-containers --selector=app=ocr-worker
          kubectl logs --all-containers --selector=app=ocr-worker --previous || true
          echo '[project-overengineer-fe logs]'
          kubectl logs --all-containers --selector=app=project-overengineer-fe
          kubectl logs --all-containers --selector=app=project-overengineer-fe --previous || true
          echo '[loki logs]'
          kubectl logs -n monitoring-plane --all-containers --selector=app=loki
          kubectl logs -n monitoring-plane --all-containers --selector=app=loki --previous || true
          echo '[mimir logs]'
          kubectl logs -n monitoring-plane --all-containers --selector=app=mimir
          kubectl logs -n monitoring-plane --all-containers --selector=app=mimir --previous || true
          echo '[alloy logs]'
          kubectl logs -n monitoring-plane --all-containers --selector=app=alloy
          kubectl logs -n monitoring-plane --all-containers --selector=app=alloy --previous || true
          echo '[grafana logs]'
          kubectl logs -n monitoring-plane --all-containers --selector=app=grafana
          kubectl logs -n monitoring-plane --all-containers --selector=app=grafana --previous || true

      - name: Kubernetes cleanup (before terraform destroy)
        if: ${{ github.event.inputs.should_destroy == 'yes' }}
        run: |
          kubectl delete all --all --ignore-not-found=true
          kubectl delete pvc --all --ignore-not-found=true || true
          kubectl delete all -n monitoring-plane --all --ignore-not-found=true || true
          kubectl delete pvc -n monitoring-plane --all --ignore-not-found=true || true

      - name: Configure AWS credentials (before terraform destroy)
        if: ${{ github.event.inputs.should_destroy == 'yes' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Terraform destroy
        if: ${{ github.event.inputs.should_destroy == 'yes' }}
        run: terraform destroy -auto-approve
        working-directory: ./terraform/environment/staging

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.3

      - name: Terraform init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ./terraform/environment/production

      - name: Terraform apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ./terraform/environment/production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-eks-prod
          aws-region: us-east-2

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name project-overengineer-prod \
            --region us-east-2

      - name: Apply default storage class to AWS
        run: kubectl apply -f k8s-aws-default-sc.yaml

      - name: Create monitoring plane namespace
        run: kubectl apply -f monitoring-plane-namespace.yaml

      - name: Deploy vault
        run: kubectl apply -f vault/service.yaml

      - name: Wait for vault apply (max 90s)
        run: kubectl rollout status statefulset/vault --timeout=90s

      - name: Deploy alloy
        run: kubectl apply -f alloy/daemonset.yaml

      - name: Deploy redis-master, redis-replica, redis-sentinel
        run: kubectl apply -f redis/service.yaml
      
      - name: Deploy janitor
        run: kubectl apply -f janitor/service.yaml
      
      - name: Deploy status-api
        run: kubectl apply -f status-api/service.yaml

      - name: Deploy ocr-worker, ollama-ocr
        run: kubectl apply -f ocr-worker/service.yaml

      - name: Deploy project-overengineer-fe
        run: kubectl apply -f project-overengineer-fe/service.yaml

      - name: Wait for apply (max 300s/service)
        run: |
          echo '[waiting for redis-master]'
          kubectl rollout status statefulset/redis-master --timeout=300s
          echo '[waiting for redis-replica]'
          kubectl rollout status statefulset/redis-replica --timeout=300s
          echo '[waiting for redis-sentinel]'
          kubectl rollout status deployment/redis-sentinel --timeout=300s
          echo '[waiting for janitor]'
          kubectl rollout status deployment/janitor --timeout=300s
          echo '[waiting for status-api]'
          kubectl rollout status deployment/status-api --timeout=300s
          echo '[waiting for ocr-worker, ollama-ocr]'
          kubectl rollout status statefulset/ocr-worker --timeout=300s
          echo '[waiting for project-overengineer-fe]'
          kubectl rollout status statefulset/project-overengineer-fe --timeout=300s

      - name: Deploy loki
        run: kubectl apply -f loki/service.yaml

      - name: Deploy mimir
        run: kubectl apply -f mimir/service.yaml

      - name: Deploy grafana
        run: kubectl apply -f grafana/service.yaml

      - name: Wait for apply (max 300s/service)
        run: |
          echo '[waiting for loki]'
          kubectl rollout status -n monitoring-plane statefulset/loki --timeout=300s
          echo '[waiting for mimir]'
          kubectl rollout status -n monitoring-plane statefulset/mimir --timeout=300s
          echo '[waiting for alloy]'
          kubectl rollout status -n monitoring-plane daemonset/alloy --timeout=300s
          echo '[waiting for grafana]'
          kubectl rollout status -n monitoring-plane statefulset/grafana --timeout=300s

      - name: Dump logs (if apply failed)
        if: failure()
        run: |
          echo 'Dumping logs...'
          echo '[vault logs]'
          kubectl logs --all-containers --selector=app=vault
          kubectl logs --all-containers --selector=app=vault --previous || true
          kubectl logs vault-0 -c vault-init || true
          echo '[redis-master logs]'
          kubectl logs --all-containers --selector=app=redis-master
          kubectl logs --all-containers --selector=app=redis-master --previous || true
          echo '[redis-replica logs]'
          kubectl logs --all-containers --selector=app=redis-replica
          kubectl logs --all-containers --selector=app=redis-replica --previous || true
          echo '[redis-sentinel logs]'
          kubectl logs --all-containers --selector=app=redis-sentinel
          kubectl logs --all-containers --selector=app=redis-sentinel --previous || true
          echo '[janitor logs]'
          kubectl logs --all-containers --selector=app=janitor
          kubectl logs --all-containers --selector=app=janitor --previous || true
          echo '[status-api logs]'
          kubectl logs --all-containers --selector=app=status-api
          kubectl logs --all-containers --selector=app=status-api --previous || true
          echo '[ocr-worker, ollama-ocr logs]'
          kubectl logs --all-containers --selector=app=ocr-worker
          kubectl logs --all-containers --selector=app=ocr-worker --previous || true
          echo '[project-overengineer-fe logs]'
          kubectl logs --all-containers --selector=app=project-overengineer-fe
          kubectl logs --all-containers --selector=app=project-overengineer-fe --previous || true
          echo '[loki logs]'
          kubectl logs -n monitoring-plane --all-containers --selector=app=loki
          kubectl logs -n monitoring-plane --all-containers --selector=app=loki --previous || true
          echo '[mimir logs]'
          kubectl logs -n monitoring-plane --all-containers --selector=app=mimir
          kubectl logs -n monitoring-plane --all-containers --selector=app=mimir --previous || true
          echo '[alloy logs]'
          kubectl logs -n monitoring-plane --all-containers --selector=app=alloy
          kubectl logs -n monitoring-plane --all-containers --selector=app=alloy --previous || true
          echo '[grafana logs]'
          kubectl logs -n monitoring-plane --all-containers --selector=app=grafana
          kubectl logs -n monitoring-plane --all-containers --selector=app=grafana --previous || true

      - name: Kubernetes cleanup (before terraform destroy)
        if: ${{ github.event.inputs.should_destroy == 'yes' }}
        run: |
          kubectl delete all --all --ignore-not-found=true
          kubectl delete pvc --all --ignore-not-found=true || true
          kubectl delete all -n monitoring-plane --all --ignore-not-found=true || true
          kubectl delete pvc -n monitoring-plane --all --ignore-not-found=true || true

      - name: Configure AWS credentials (before terraform destroy)
        if: ${{ github.event.inputs.should_destroy == 'yes' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Terraform destroy
        if: ${{ github.event.inputs.should_destroy == 'yes' }}
        run: terraform destroy -auto-approve
        working-directory: ./terraform/environment/production
